// The vendored diagram renderer.
//
// The artifact is committed, so the thing worth testing is that what is
// committed is what the build produces, and that it has not quietly changed
// size. A dependency bump that doubles a 3.4 MB asset is a decision, and it
// should have to be made deliberately rather than arrive with a lockfile.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { build } from '../scripts/build-mermaid.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'server', 'public', 'mermaid.js');

// Bounds, not an exact size: a patch release moves the byte count and should not
// fail the suite. Doubling or halving it is the event worth catching, in both
// directions, because a truncated bundle is as broken as a bloated one.
const MIN_BYTES = 2.5 * 1024 * 1024;
const MAX_BYTES = 4.5 * 1024 * 1024;

test('the vendored bundle is committed', () => {
  assert.ok(existsSync(OUT), 'server/public/mermaid.js is checked in; run scripts/build-mermaid.mjs');
});

test('it carries the generated header, a version, and the upstream licence', () => {
  const src = readFileSync(OUT, 'utf8');
  assert.match(src, /Vendored diagram renderer: Mermaid \d+\.\d+\.\d+, MIT/);
  assert.match(src, /Generated by scripts\/build-mermaid\.mjs\. Do not edit\./);
  assert.match(src, /--- upstream licence ---/);
  assert.match(src, /Permission is hereby granted, free of charge/, 'the MIT text itself, not just the word');
});

test('it is within the size bounds it was accepted at', () => {
  const bytes = readFileSync(OUT).length;
  const mb = (bytes / 1024 / 1024).toFixed(2);
  assert.ok(bytes > MIN_BYTES, `${mb} MB is smaller than expected; a truncated bundle renders nothing`);
  assert.ok(bytes < MAX_BYTES, `${mb} MB is larger than the accepted bound; that is a decision, not a lockfile change`);
});

test('the committed bytes are what the build produces', () => {
  const before = readFileSync(OUT);
  const r = build();
  assert.deepEqual(readFileSync(OUT), before, 'rebuilding changed the artifact; commit the rebuild');
  assert.equal(r.bytes, before.length);
  assert.ok(r.gzip < r.bytes, 'the reported gzip size is a real compression, not a copy');
});

test('nothing in it runs on load', () => {
  const src = readFileSync(OUT, 'utf8');
  // Mermaid's own auto-run would render on DOMContentLoaded, before review.js
  // has decided which blocks are diagrams and before the block reconcile expects
  // the page to change shape. The UMD bundle only runs when called.
  assert.doesNotMatch(src, /mermaid\.initialize\(\{[^}]*startOnLoad\s*:\s*true/);
});
