// The component library's source of truth and the stylesheet generated from it.
//
// The whole design rests on one property: the definitions, the stylesheet, the
// lint registry, the commentability allow-list and the markdown export map all
// derive from one place. These tests hold that property. Drift between any two
// of them is the failure the library exists to prevent, and it is exactly what
// produced the three hard-coded component lists already in the codebase.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  COMPONENTS, FAMILIES, TONES, componentClasses, blockComponents, noticeTypes,
} from '../components/index.mjs';
import { buildCss } from '../lib/components-build.mjs';
import { PALETTE_TOKENS } from '../lib/config.mjs';

/** Class selectors a stylesheet defines, ignoring pseudo-elements and states. */
function definedClasses(css) {
  const out = new Set();
  for (const m of css.matchAll(/\.([a-zA-Z][\w-]*)/g)) out.add(m[1]);
  return out;
}

// ---- the agreement ----

test('every component with a class is defined by the generated stylesheet', () => {
  const css = buildCss();
  const defined = definedClasses(css);
  const missing = COMPONENTS.filter((c) => c.kind === 'class' && !defined.has(c.name));
  assert.deepEqual(missing.map((c) => c.name), [], 'a component the stylesheet does not style');
});

test('every class the stylesheet defines is a registered component or a variant of one', () => {
  const css = buildCss();
  const known = new Set([...componentClasses(), ...COMPONENTS.flatMap((c) => c.variants || [])]);
  const stray = [...definedClasses(css)].filter((n) => !known.has(n));
  assert.deepEqual(stray, [], 'a class in the stylesheet that no definition registers');
});

test('the build is deterministic: twice is byte-identical', () => {
  assert.equal(buildCss(), buildCss());
});

test('the stylesheet carries its markers and a version', () => {
  const css = buildCss();
  assert.match(css, /specforge:components v\d+ start/, 'opening marker with a version');
  assert.match(css, /specforge:components end/, 'closing marker');
  assert.ok(css.indexOf('start') < css.indexOf('end'), 'in that order');
});

// ---- the palette contract (house rules, enforced by the spec lint) ----

test('every color in the stylesheet is a palette token or a mix of one', () => {
  const css = buildCss();
  // A literal color anywhere means a spec cannot be re-themed by overriding the
  // canonical tokens, which is what the review layer's theme variants do.
  const literals = [...css.matchAll(/#[0-9a-fA-F]{3,8}\b|\brgba?\(/g)].map((m) => m[0]);
  assert.deepEqual(literals, [], 'a literal color in a component definition');

  const tokens = [...css.matchAll(/var\(--([\w-]+)/g)].map((m) => m[1]);
  const foreign = [...new Set(tokens)].filter((t) => !PALETTE_TOKENS.includes(t));
  assert.deepEqual(foreign, [], 'a custom property outside the canonical palette');
});

// ---- the definitions themselves ----

test('every definition carries what all five consumers need', () => {
  for (const c of COMPONENTS) {
    assert.ok(c.name, 'a name');
    assert.ok(FAMILIES.includes(c.family), `${c.name}: a known family, got ${c.family}`);
    assert.ok(['class', 'element'].includes(c.kind), `${c.name}: kind is class or element`);
    assert.ok(c.rule && c.rule.length > 20, `${c.name}: a rule saying when it applies`);
    assert.ok(c.example && c.example.includes('<'), `${c.name}: markup showing its use`);
    if (c.kind === 'class') assert.ok(c.css, `${c.name}: css`);
  }
});

// The count is pinned so it moves deliberately. It has moved twice: the mermaid
// spec added `pre[data-lang="mermaid"]` to structure, making 35 across 6; then
// the heading family added h2/h3/h4/h5, making 39 across 7. Headings were used
// 4,536 times across the store before anything defined them.
test('the inventory is 39 components across 7 families', () => {
  assert.equal(COMPONENTS.length, 39);
  assert.deepEqual(
    FAMILIES.map((f) => [f, COMPONENTS.filter((c) => c.family === f).length]),
    [['heading', 4], ['notice', 12], ['inline', 7], ['data', 4], ['code', 2], ['structure', 7], ['spec', 3]],
  );
});

// Tone is what the notice looks like; the type is what it means. An author picks
// the type, never the tone, which is the change that removes the 273 typeless
// callouts measured in the store.
test('every notice carries exactly one tone and a generated label', () => {
  const notices = COMPONENTS.filter((c) => c.family === 'notice');
  assert.equal(notices.length, 12);
  for (const n of notices) {
    assert.ok(TONES.includes(n.tone), `${n.name}: a known tone, got ${n.tone}`);
    assert.ok(n.label, `${n.name}: a label`);
    assert.match(buildCss(), new RegExp(`\\.callout\\.${n.name}::before\\{content:"${n.label}"\\}`),
      `${n.name}: the label is generated by CSS, so it cannot be retyped per spec`);
  }
});

test('noticeTypes is the list the markdown exporter and the lint both read', () => {
  assert.deepEqual(noticeTypes().sort(), [
    'assumption', 'constraint', 'danger', 'decision', 'deviation', 'example',
    'note', 'quote', 'risk', 'success', 'tip', 'warning',
  ]);
});

// The commentability check hard-codes .card/.panel/.stat/.callout today, which is
// why .evidence tripped it during design. It derives from here instead.
test('blockComponents covers the blocks a reviewer can comment on', () => {
  const blocks = blockComponents();
  for (const expected of ['callout', 'panel', 'card', 'stat', 'evidence']) {
    assert.ok(blocks.includes(expected), `${expected} is commentable`);
  }
  assert.ok(!blocks.includes('kw'), 'an inline component is not a comment target');
});

// A dispatch table with Object.prototype behind it answers to names nobody
// registered: `components constructor` resolved the Function constructor,
// called it, and exited 0 printing {}. Both tables are null-prototype now.
test('a command name off Object.prototype is not a command', async () => {
  const { execFile } = await import('node:child_process');
  const { promisify } = await import('node:util');
  const run = promisify(execFile);
  const cli = new URL('../lib/specforge-cli.mjs', import.meta.url).pathname;

  for (const argv of [['components', 'constructor'], ['components', '__proto__'], ['constructor'], ['toString']]) {
    await assert.rejects(
      () => run(process.execPath, [cli, ...argv]),
      (err) => {
        assert.ok(err.code > 0, `${argv.join(' ')} exits non-zero, got ${err.code}`);
        assert.match(err.stderr, /unknown (command|subcommand)/, `${argv.join(' ')} says it is unknown`);
        return true;
      },
      `${argv.join(' ')} is refused`,
    );
  }
});

test('no two components share a name', () => {
  const names = COMPONENTS.map((c) => c.name);
  assert.deepEqual(names.length, new Set(names).size, 'duplicate component name');
});
