// The skill id as the running harness resolves it — the review loop's
// work-addressing seam. Claude Code namespaces plugin skills and its Skill tool
// accepts only the ids it lists (a bare name is "Unknown skill" there); Pi has
// no namespace and rejects a colon in a skill name. The hook texts are
// generated by processes that already know which harness they serve, and say so
// with SPECFORGE_HARNESS.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { skillRef, PI_HARNESS } from '../lib/skill-ref.mjs';

test('namespaces the skill for Claude Code', () => {
  assert.equal(skillRef('review-spec', { CLAUDE_CODE_SESSION_ID: 'cc-1' }), 'specforge:review-spec');
});

test('default (no marker) keeps the Claude form', () => {
  // A bare `node` run, CI, or the test suite: no harness signal, so the
  // strict id — the one the Skill tool's contract accepts — not the guess.
  assert.equal(skillRef('review-spec', {}), 'specforge:review-spec');
});

test('the bare name where Pi is the harness', () => {
  assert.equal(skillRef('review-spec', { SPECFORGE_HARNESS: PI_HARNESS }), 'review-spec');
});

test('a session-id override is not a harness signal', () => {
  // The defect this closes. SPECFORGE_SESSION_ID is the harness-NEUTRAL session
  // override (hooks/lib/session.mjs), and lib/specforge-cli.mjs names it to the
  // user when wait-batch cannot find an id. A Claude Code user who arms a
  // watcher from a plain terminal sets it, and used to be told to run a bare
  // skill name their own Skill tool answers with "Unknown skill".
  assert.equal(skillRef('review-spec', { SPECFORGE_SESSION_ID: 'sf-1' }), 'specforge:review-spec');
});

test('an unrecognised harness value is not Pi', () => {
  // Only the value Pi sets means Pi. A future harness that stamps its own name
  // gets the strict id until it is taught here, rather than the wrong one.
  assert.equal(skillRef('export', { SPECFORGE_HARNESS: 'something-else' }), 'specforge:export');
});

test('the harness marker decides even beside a Claude session id', () => {
  // A Pi session on a machine that also exports Claude's env still tells its
  // agent the id Pi can run.
  assert.equal(skillRef('export', {
    SPECFORGE_HARNESS: PI_HARNESS, CLAUDE_CODE_SESSION_ID: 'cc-1',
  }), 'export');
});
