// The skill id as the running harness resolves it — the review loop's
// work-addressing seam. Claude Code namespaces plugin skills and its Skill tool
// accepts only the ids it lists (a bare name is "Unknown skill" there); Pi has
// no namespace and rejects a colon in a skill name. The hook texts are
// generated by processes that already know which harness they serve —
// SPECFORGE_SESSION_ID is Pi's marker, set by its extension for everything it
// runs in-process or spawns (#256); Claude Code exports
// CLAUDE_CODE_SESSION_ID into every hook and Bash subprocess instead.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { skillRef } from '../lib/skill-ref.mjs';

test('namespaces the skill for Claude Code', () => {
  assert.equal(skillRef('review-spec', { CLAUDE_CODE_SESSION_ID: 'cc-1' }), 'specforge:review-spec');
});

test('default (no Pi marker) keeps the Claude form', () => {
  // A bare `node` run, CI, or the test suite: no harness signal, so the
  // strict id — the one the Skill tool's contract accepts — not the guess.
  assert.equal(skillRef('review-spec', {}), 'specforge:review-spec');
});

test('the bare name where Pi is the harness', () => {
  assert.equal(skillRef('review-spec', { SPECFORGE_SESSION_ID: 'pi-1' }), 'review-spec');
});

test('the Pi marker wins when both harness vars are present', () => {
  // #256 made SPECFORGE_SESSION_ID resolve ahead of Claude's env; the skill
  // name follows the same precedence, so a Pi session on a machine that also
  // has Claude env exported never tells its agent to run the CC id.
  assert.equal(skillRef('export', {
    SPECFORGE_SESSION_ID: 'pi-1', CLAUDE_CODE_SESSION_ID: 'cc-1',
  }), 'export');
});