// Generates the component stylesheet from the definitions in components/.
//
// Output is deterministic: the definitions are an ordered array and nothing here
// reads a clock, a directory listing, or an object's key order. That matters
// because `components sync --all` re-stamps every spec in the store, and a
// generator that reordered its output would rewrite files that had not changed.

import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { COMPONENTS, BASE_CSS } from '../components/index.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * The stylesheet version. Bump when the generated CSS changes in a way a spec
 * should pick up; `sync` compares this against what a spec carries.
 */
export const VERSION = 1;

export const START = `/* specforge:components v${VERSION} start: generated by components build, do not edit */`;
export const END = '/* specforge:components end */';

/** Path of the generated stylesheet. */
export function cssPath() {
  return join(ROOT, 'templates', 'components.css');
}

/**
 * The stylesheet, markers included.
 *
 * Families are emitted in definition order with a comment header each, so the
 * generated file reads like something a person could have written. A spec author
 * opening a spec sees this block before their own styles.
 */
export function buildCss() {
  const out = [START, '', BASE_CSS, ''];
  let family = null;
  for (const c of COMPONENTS) {
    if (!c.css) continue; // elements carry a rule and an example, not a class
    if (c.family !== family) {
      family = c.family;
      out.push(`/* ${family} */`);
    }
    out.push(c.css);
  }
  out.push('', END, '');
  return out.join('\n');
}

/** Write the stylesheet. Returns what changed, so a no-op build says so. */
export function writeCss() {
  const css = buildCss();
  const path = cssPath();
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* first build */ }
  if (before === css) return { path, changed: false, bytes: css.length };
  writeFileSync(path, css);
  return { path, changed: true, bytes: css.length };
}

/** `specforge components build`. */
export function cmdComponentsBuild() {
  const css = writeCss();
  return {
    version: VERSION,
    components: COMPONENTS.length,
    css: { path: css.path, bytes: css.bytes, changed: css.changed },
  };
}
