// Generates the component stylesheet from the definitions in components/.
//
// Output is deterministic: the definitions are an ordered array and nothing here
// reads a clock, a directory listing, or an object's key order. That matters
// because `components sync --all` re-stamps every spec in the store, and a
// generator that reordered its output would rewrite files that had not changed.

import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { COMPONENTS, BASE_CSS, BASE_CLASSES, LIVE_ATTR } from '../components/index.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * The stylesheet version. Bump when the generated CSS changes in a way a spec
 * should pick up; `sync` compares this against what a spec carries.
 */
export const VERSION = 2;

export const START = `/* specforge:components v${VERSION} start: generated by components build, do not edit */`;

/**
 * The closing marker carries a hash of the block body.
 *
 * Without it there is no way to tell a spec still carrying an older version from
 * one somebody edited by hand, and the two need opposite treatment: the first is
 * re-stamped, the second is refused.
 */
export function endMarker(body) {
  return `/* specforge:components end sha=${blockHash(body)} */`;
}

/** First 8 hex of the sha256 of the block body, whitespace normalised at the ends. */
export function blockHash(body) {
  return createHash('sha256').update(body.trim()).digest('hex').slice(0, 8);
}

/** Path of the generated stylesheet. */
export function cssPath() {
  return join(ROOT, 'templates', 'components.css');
}

/**
 * The stylesheet, markers included.
 *
 * Families are emitted in definition order with a comment header each, so the
 * generated file reads like something a person could have written. A spec author
 * opening a spec sees this block before their own styles.
 */
export function buildCss() {
  const body = buildBody();
  return [START, '', body, '', endMarker(body), ''].join('\n');
}

/** The rules themselves, without the markers. This is what the hash covers. */
export function buildBody() {
  const out = [BASE_CSS, ''];
  let family = null;
  for (const c of COMPONENTS) {
    if (!c.css) continue; // elements carry a rule and an example, not a class
    if (c.family !== family) {
      family = c.family;
      out.push(`/* ${family} */`);
    }
    out.push(c.css);
  }
  return out.join('\n');
}

/**
 * Rules in the stamped stylesheet that hide content with nothing to bring it
 * back. The machine-checkable half of the enhancement contract (I1).
 *
 * A rule may hide freely under `[data-sf-live]`, which only the served script
 * sets: the un-enhanced document still shows everything. Anywhere else, hiding
 * is permanent for a reader who opened the file from disk, and silent.
 *
 * Pseudo-element selectors are exempt. A `::before`, a `::after` or a details
 * marker is decoration a component draws or suppresses, not content a reader
 * came for, and the disclosure legitimately hides the native triangle to draw
 * its own.
 *
 * @param {string} css the stylesheet body
 * @returns {string[]} offending selectors, empty when the contract holds
 */
export function hidingRules(css) {
  const out = [];
  for (const chunk of css.replace(/\/\*[\s\S]*?\*\//g, '').split('}')) {
    const parts = chunk.split('{');
    if (parts.length < 2) continue;
    const body = parts[parts.length - 1];
    if (!/(?:^|;|\s)display\s*:\s*none|visibility\s*:\s*hidden/.test(body)) continue;
    for (const s of parts[parts.length - 2].split(',')) {
      const sel = s.trim();
      if (!sel || sel.startsWith('@')) continue;
      if (sel.includes(`[${LIVE_ATTR}]`)) continue;
      if (sel.includes('::')) continue;
      out.push(sel);
    }
  }
  return out;
}

/** Write the stylesheet. Returns what changed, so a no-op build says so. */
export function writeCss() {
  const css = buildCss();
  const path = cssPath();
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* first build */ }
  if (before === css) return { path, changed: false, bytes: css.length };
  writeFileSync(path, css);
  return { path, changed: true, bytes: css.length };
}

/**
 * Templates that carry the stamped block.
 *
 * All five, the deck included. It defined 11 of the library's classes itself
 * until its own definitions were removed; what it keeps is slide layout and the
 * wireframe primitives the library has no equivalent for, plus two scoped
 * adjustments for the surface a slide is.
 */
export const STAMPED_TEMPLATES = [
  'spec-base.html',
  'spec-base-doc.html',
  'spec-base-general.html',
  'spec-base-research.html',
  'spec-base-deck.html',
];

/**
 * Whether a new spec of this type is stamped at creation. Always.
 *
 * Stamping follows the SHELL, not the kind, and every shell above carries the
 * library. This used to be a list of the six kinds, which was the same answer
 * written a second way; once a kind could be added from the browser (spec
 * 45395008a2) the two stopped agreeing, and a custom kind would have created
 * specs with no component CSS at all.
 *
 * Kept as a function rather than deleted at the call site: what it answers is a
 * real question, and the day one shell stops carrying the library the answer
 * belongs here rather than being rediscovered.
 */
export function stampsAtCreate() {
  return true;
}

/** Path of the generated shell-vocabulary module. */
export function shellClassesPath() {
  return join(ROOT, 'lib', 'shell-classes.mjs');
}

/**
 * Every selector in a stylesheet, comments and at-rule preludes excluded.
 *
 * The segment before the LAST brace of a block, not the first: a rule written
 * compactly inside an at-rule, `@media (max-width:900px){.fs-group{...}}`, puts
 * the at-rule where a naive parse looks for the selector, and the class inside it
 * is never seen. Two things read this — the generated vocabulary and the
 * duplication test — so the blind spot both hid a shell class and let a
 * redefinition through.
 */
export function selectors(css) {
  const out = [];
  for (const chunk of css.replace(/\/\*[\s\S]*?\*\//g, '').split('}')) {
    const parts = chunk.split('{');
    if (parts.length < 2) continue;
    for (const s of parts[parts.length - 2].split(',')) {
      const t = s.trim();
      if (t && !t.startsWith('@')) out.push(t);
    }
  }
  return out;
}

/**
 * The classes the shells define themselves, outside the stamped block.
 *
 * These are not components and they are not drift: a slide, a filmstrip and a
 * table of contents are the shell a spec is built in, and the library does not
 * extend into layout. The lint needs to tell them from an invented class, and
 * before this it did so from a hand-picked list of eight that was already wrong
 * about the deck's 43.
 */
export function shellClasses() {
  const owned = new Set([
    ...BASE_CLASSES,
    ...COMPONENTS.flatMap((c) => [c.kind === 'class' ? c.name : null, ...(c.variants || [])]).filter(Boolean),
  ]);
  const out = new Set();
  for (const name of STAMPED_TEMPLATES) {
    const html = readFileSync(join(ROOT, 'templates', name), 'utf8');
    const style = html.split('specforge:components end')[1];
    if (!style) continue;
    const own = style.split('</style>')[0];
    for (const selector of selectors(own)) {
      for (const m of selector.matchAll(/\.([a-zA-Z][\w-]*)/g)) {
        // A shell may adjust a library component where it sits (`.slide .svg-box`).
        // That names the component, it does not add to the shell's vocabulary.
        if (!owned.has(m[1])) out.add(m[1]);
      }
    }
  }
  return [...out].sort();
}

/** Write the shell vocabulary as a module the lint imports. */
export function writeShellClasses() {
  const classes = shellClasses();
  const body = `// Generated by \`specforge components build\`. Do not edit.
//
// Every class the bundled shells define outside the stamped block: slide layout,
// filmstrip, table of contents, and the rest of the chrome a spec is authored
// in. Derived rather than listed, so a template that grows a class does not
// silently start failing the lint that reads this.

export const SHELL_CLASSES = new Set(${JSON.stringify(classes, null, 2).replace(/\n/g, '\n  ')});
`;
  const path = shellClassesPath();
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* first build */ }
  if (before === body) return { path, changed: false, count: classes.length };
  writeFileSync(path, body);
  return { path, changed: true, count: classes.length };
}

/** `specforge components build`. Regenerates every artifact derived from the definitions. */
export async function cmdComponentsBuild() {
  const css = writeCss();
  // Imported here rather than at module scope: the stamp reads the CSS this
  // module generates, and a cycle at load time would leave one of them empty.
  const { stampFile } = await import('./components-stamp.mjs');
  const { writeRules } = await import('./components-rules.mjs');
  const { writeDoc } = await import('./components-doc.mjs');
  const templates = STAMPED_TEMPLATES.map((name) => {
    const r = stampFile(join(ROOT, 'templates', name), { force: true });
    return { name, changed: r.changed };
  });
  const rules = writeRules();
  const docs = writeDoc();
  // After the templates: it reads what they define outside the block they were
  // just stamped with.
  const shell = writeShellClasses();
  return {
    version: VERSION,
    components: COMPONENTS.length,
    css: { path: css.path, bytes: css.bytes, changed: css.changed },
    rules: { path: rules.path, bytes: rules.bytes, changed: rules.changed },
    docs: docs.map((d) => ({ layer: d.layer, path: d.path, changed: d.changed })),
    shell: { path: shell.path, count: shell.count, changed: shell.changed },
    templates,
  };
}
