// Generates the component stylesheet from the definitions in components/.
//
// Output is deterministic: the definitions are an ordered array and nothing here
// reads a clock, a directory listing, or an object's key order. That matters
// because `components sync --all` re-stamps every spec in the store, and a
// generator that reordered its output would rewrite files that had not changed.

import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { COMPONENTS, BASE_CSS } from '../components/index.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * The stylesheet version. Bump when the generated CSS changes in a way a spec
 * should pick up; `sync` compares this against what a spec carries.
 */
export const VERSION = 1;

export const START = `/* specforge:components v${VERSION} start: generated by components build, do not edit */`;

/**
 * The closing marker carries a hash of the block body.
 *
 * Without it there is no way to tell a spec still carrying an older version from
 * one somebody edited by hand, and the two need opposite treatment: the first is
 * re-stamped, the second is refused.
 */
export function endMarker(body) {
  return `/* specforge:components end sha=${blockHash(body)} */`;
}

/** First 8 hex of the sha256 of the block body, whitespace normalised at the ends. */
export function blockHash(body) {
  return createHash('sha256').update(body.trim()).digest('hex').slice(0, 8);
}

/** Path of the generated stylesheet. */
export function cssPath() {
  return join(ROOT, 'templates', 'components.css');
}

/**
 * The stylesheet, markers included.
 *
 * Families are emitted in definition order with a comment header each, so the
 * generated file reads like something a person could have written. A spec author
 * opening a spec sees this block before their own styles.
 */
export function buildCss() {
  const body = buildBody();
  return [START, '', body, '', endMarker(body), ''].join('\n');
}

/** The rules themselves, without the markers. This is what the hash covers. */
export function buildBody() {
  const out = [BASE_CSS, ''];
  let family = null;
  for (const c of COMPONENTS) {
    if (!c.css) continue; // elements carry a rule and an example, not a class
    if (c.family !== family) {
      family = c.family;
      out.push(`/* ${family} */`);
    }
    out.push(c.css);
  }
  return out.join('\n');
}

/** Write the stylesheet. Returns what changed, so a no-op build says so. */
export function writeCss() {
  const css = buildCss();
  const path = cssPath();
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* first build */ }
  if (before === css) return { path, changed: false, bytes: css.length };
  writeFileSync(path, css);
  return { path, changed: true, bytes: css.length };
}

/**
 * Templates that carry the stamped block.
 *
 * The deck is absent until Stage 7: it defines 18 classes the library also
 * defines, and stamping it before those are reconciled would put two
 * definitions of a card in one file.
 */
export const STAMPED_TEMPLATES = [
  'spec-base.html',
  'spec-base-doc.html',
  'spec-base-general.html',
  'spec-base-research.html',
];

/** `specforge components build`. Regenerates every artifact derived from the definitions. */
export async function cmdComponentsBuild() {
  const css = writeCss();
  // Imported here rather than at module scope: the stamp reads the CSS this
  // module generates, and a cycle at load time would leave one of them empty.
  const { stampFile } = await import('./components-stamp.mjs');
  const { writeRules } = await import('./components-rules.mjs');
  const templates = STAMPED_TEMPLATES.map((name) => {
    const r = stampFile(join(ROOT, 'templates', name), { force: true });
    return { name, changed: r.changed };
  });
  const rules = writeRules();
  return {
    version: VERSION,
    components: COMPONENTS.length,
    css: { path: css.path, bytes: css.bytes, changed: css.changed },
    rules: { path: rules.path, bytes: rules.bytes, changed: rules.changed },
    templates,
  };
}
