// Generates references/spec-components.md: the selection rules an authoring
// agent reads before writing a spec.
//
// Generated rather than written, for the same reason the stylesheet is: a rule
// that lives apart from the component it governs goes stale, and the create-spec
// skill reads this file every time it authors. The prose in each entry comes
// from the definition itself.

import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { COMPONENTS, FAMILIES } from '../components/index.mjs';
import { VERSION } from './components-build.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export function rulesPath() {
  return join(ROOT, 'references', 'spec-components.md');
}

const FAMILY_TITLE = {
  notice: 'Notices',
  inline: 'Inline',
  data: 'Data',
  code: 'Code',
  structure: 'Structure',
  spec: 'Spec structure',
};

/**
 * The selection table: what the block asserts, and what to reach for.
 *
 * Ordered by how often the choice comes up rather than by family, because this
 * is the table an author scans mid-sentence.
 */
const SELECTION = [
  ['A choice was made between alternatives', 'callout decision'],
  ['We believe X but have not verified it', 'callout assumption'],
  ['This can fail in a specific way', 'callout risk'],
  ['We are departing from a principle or an existing pattern', 'callout deviation'],
  ['A limit exists that we cannot move', 'callout constraint'],
  ['A number, with a method behind it', 'evidence + src'],
  ['Several headline numbers at once', 'stats'],
  ['Options weighed against each other', 'table compare'],
  ['Items compared on attributes', 'table'],
  ['An ordered procedure', 'steps'],
  ['Conditions to verify in any order', 'checklist'],
  ['A requirement that is normative', 'kw'],
  ['A concrete instance of a rule', 'callout example'],
  ['Somebody else’s words', 'callout quote'],
  ['Something that will break if ignored', 'callout danger'],
  ['Something to be careful about', 'callout warning'],
  ['Context, no claim', 'callout note'],
  ['None of the above', 'a paragraph'],
];

export function buildRules() {
  const L = [];
  L.push('# SpecForge components');
  L.push('');
  L.push(`Generated by \`components build\` from \`components/\` (library v${VERSION}). Do not edit.`);
  L.push('');
  L.push('Every spec carries the component stylesheet as a stamped block, so these');
  L.push('classes are available in any spec and nothing needs importing. Pick a');
  L.push('component by asking what the block asserts. Appearance is never the entry');
  L.push('point: a notice takes a type, and its tone follows from the type.');
  L.push('');
  L.push('## Choosing');
  L.push('');
  L.push('| If the block asserts | Use |');
  L.push('|---|---|');
  for (const [when, use] of SELECTION) L.push(`| ${when} | \`${use}\` |`);
  L.push('');
  L.push('**Density.** A component is emphasis, and emphasis is a budget. No more than');
  L.push('one notice per 400 words of a section, and never two notices in immediate');
  L.push('succession: two adjacent notices are a table with two rows.');
  L.push('');

  for (const family of FAMILIES) {
    const items = COMPONENTS.filter((c) => c.family === family);
    if (!items.length) continue;
    L.push(`## ${FAMILY_TITLE[family] || family}`);
    L.push('');
    for (const c of items) {
      // A notice is never written alone: the class is `callout <type>`, and a
      // heading showing `.note` would teach the wrong markup.
      const head = c.family === 'notice' ? `\`.callout.${c.name}\``
        : c.kind === 'element' ? `\`<${c.name}>\`` : `\`.${c.name}\``;
      L.push(`### ${head}${c.tone ? ` · ${c.tone}` : ''}`);
      L.push('');
      L.push(c.rule);
      if (c.requires && c.requires.length) {
        L.push('');
        L.push(`Must contain: ${c.requires.map((r) => `${r}`).join('; ')}.`);
      }
      if (c.variants && c.variants.length) {
        L.push('');
        L.push(`Variants: ${c.variants.map((v) => `\`${v}\``).join(', ')}.`);
      }
      L.push('');
      L.push('```html');
      L.push(c.example);
      L.push('```');
      L.push('');
    }
  }
  return L.join('\n');
}

/** Write the rules file. Returns whether it changed. */
export function writeRules() {
  const md = buildRules();
  const path = rulesPath();
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* first build */ }
  if (before === md) return { path, changed: false, bytes: md.length };
  writeFileSync(path, md);
  return { path, changed: true, bytes: md.length };
}
