// Build the vendored diagram renderer served at /public/mermaid.js.
//
//   node scripts/build-mermaid.mjs
//
// Mermaid's ESM build code-splits its diagram types and fetches them on demand.
// A spec page cannot fetch (a published copy is behind a tunnel, and the daemon
// serves /public/<file> with no subpaths), so the vendored artifact is the UMD
// bundle, which carries every diagram type in one file. That is why this is
// 3.4 MB and prism.js is 34 KB: mermaid has to bring its layout engines with it.
//
// The cost is paid by a reader who opens a spec that actually has a diagram, and
// by nobody else. review.js appends this script only when a block declares the
// mermaid language, the same bargain the highlighter and the web fonts make.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'node_modules', 'mermaid');
const OUT = join(ROOT, 'server', 'public', 'mermaid.js');

const read = (rel) => readFileSync(join(SRC, rel), 'utf8');

export function build() {
  const version = JSON.parse(read('package.json')).version;

  // startOnLoad is not set here. Mermaid's own auto-run would render on
  // DOMContentLoaded, before review.js has decided which blocks are diagrams and
  // before the block reconcile expects the page to change shape. review.js calls
  // render() itself, for the same reason prism is vendored with manual: true.
  const header = `/* Vendored diagram renderer: Mermaid ${version}, MIT.
 *
 * Generated by scripts/build-mermaid.mjs. Do not edit. The upstream licence is
 * reproduced at the end of this file.
 *
 * The UMD bundle, not the ESM one: the ESM build code-splits its diagram types
 * and fetches them on demand, and a spec page has nowhere to fetch from.
 *
 * Nothing here runs on load. review.js owns when a diagram renders, because the
 * block reconcile must not see a page mid-change.
 */
`;

  const out = `${header}${read(join('dist', 'mermaid.min.js'))}
/* --- upstream licence --- */
/*
${read('LICENSE').trim()}
*/
`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, out);
  // Byte length, not string length: the bundle carries multi-byte characters, so
  // the two differ by 141 bytes here and only one of them is the size of the file
  // or of the transfer.
  return { path: OUT, version, bytes: Buffer.byteLength(out), gzip: gzipSync(out).length };
}

// Only when run directly, so a test can import build() without writing a file.
if (process.argv[1] && process.argv[1].endsWith('build-mermaid.mjs')) {
  const r = build();
  const mb = (r.bytes / 1024 / 1024).toFixed(2);
  const kb = (r.gzip / 1024).toFixed(0);
  console.log(`${r.path}  mermaid ${r.version}  ${mb} MB raw, ${kb} KB gzipped`);
}
