// Build the vendored highlighter served at /public/prism.js.
//
//   node scripts/build-prism.mjs
//
// Prism ships one file per grammar and a loader that fetches them; a spec page
// cannot fetch (a published copy is behind a tunnel, and the daemon serves
// /public/<file> with no subpaths), so the grammars are concatenated into one
// file at build time. Which grammars is not a guess: LANGUAGES is what the store
// actually contains, measured by scripts/guess-specforge-codeblock-langs.mjs,
// plus the ones an author reaches for next.
//
// Autoloading and worker support are stripped: both would fetch.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'node_modules', 'prismjs');
const OUT = join(ROOT, 'server', 'public', 'prism.js');

/**
 * The grammars, in dependency order (Prism has no loader here, so a grammar that
 * extends another must come after it).
 *
 * Measured share of the 133 code blocks in the store: python 24%, yaml 15%,
 * javascript 3%, markup 2%, bash 2%, json 2%, diff 2%, sql 1%. The rest are
 * pseudo-code and ASCII diagrams, which is why nothing here is ever applied
 * without an author declaring the language.
 */
export const LANGUAGES = [
  'markup', 'css', 'clike', 'javascript', // Prism's four defaults, always present
  'python', 'yaml', 'json', 'bash', 'sql', 'typescript', 'diff',
];

const read = (rel) => readFileSync(join(SRC, rel), 'utf8');

const HEADER = `/* Vendored highlighter: Prism ${JSON.parse(read('package.json')).version}, MIT.
 *
 * Generated by scripts/build-prism.mjs — do not edit. Rebuild after changing
 * LANGUAGES there. The upstream licence is reproduced at the end of this file.
 *
 * Grammars: ${LANGUAGES.join(', ')}
 *
 * manual: true, so Prism never highlights on DOMContentLoaded. review.js decides
 * what gets highlighted, and it only ever touches a block whose author declared a
 * language.
 */
var _self = typeof window !== 'undefined' ? window : {};
_self.Prism = { manual: true, disableWorkerMessageHandler: true };
`;

// The minified core and one minified file per grammar. The package root's
// prism.js is the unminified dev build with the four defaults inlined, and using
// it costs 50 KB for the same behaviour.
const parts = [HEADER, read(join('components', 'prism-core.min.js'))];
for (const lang of LANGUAGES) {
  parts.push(`\n/* --- ${lang} --- */\n`, read(join('components', `prism-${lang}.min.js`)));
}
parts.push(`\n/* --- upstream licence --- */\n/*\n${read('LICENSE').trim()}\n*/\n`);

mkdirSync(dirname(OUT), { recursive: true });
const out = parts.join('\n');
writeFileSync(OUT, out);
console.log(`${OUT}  ${(out.length / 1024).toFixed(1)} KB  ${LANGUAGES.length} grammars`);
